# Generated by Django 6.0.2 on 2026-03-30 21:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward — drop old time column and add new datetime column
            sql="""
                ALTER TABLE votes DROP COLUMN IF EXISTS "time";
                ALTER TABLE votes ADD COLUMN "time" timestamp with time zone DEFAULT now() NOT NULL;
            """,
            # Reverse — undo
            reverse_sql="""
                ALTER TABLE votes DROP COLUMN IF EXISTS "time";
                ALTER TABLE votes ADD COLUMN "time" time NOT NULL;
            """
        ),
    ]
