# Generated by Django 6.0.2 on 2026-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='voter',
            name='national_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
